# Generated by Django 6.0.1 on 2026-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
    ]
