# Generated by Django 6.0.1 on 2026-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('driving_license', 'Driving License'), ('passport', 'Passport')], default='aadhar', max_length=50)),
                ('document_number', models.CharField(max_length=255)),
                ('document_image', models.ImageField(blank=True, help_text='Front side of ID document', null=True, upload_to='worker_documents/%Y/%m/%d/')),
                ('document_image_back', models.ImageField(blank=True, help_text='Back side of ID document', null=True, upload_to='worker_documents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worker_document_verification',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
