"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from .env file
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default: str = '') -> list[str]:
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# PUT YOUR REAL SECRET_KEY IN .env — generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', False)

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,10.0.2.2,testserver')

# Render provides this env var for deployed service hostname.
_render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_hostname and _render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_hostname)

if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')
if DEBUG and '*' not in ALLOWED_HOSTS:
    # Keep local development flexible without blocking emulator/LAN traffic.
    ALLOWED_HOSTS.append('*')

# CORS + CSRF settings
CORS_ALLOW_ALL_ORIGINS = _env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = _env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:8080,http://localhost:3000,http://127.0.0.1:8080',
)
CORS_ALLOW_CREDENTIALS = _env_bool('CORS_ALLOW_CREDENTIALS', False)
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'rest_framework.authtoken',  # Token authentication for REST API
    'corsheaders',  # For Flutter API calls
    'authentication',  # User authentication app
    'workers',  # Worker domain
    'services',  # Services catalog
    'bookings',  # Booking management
    'payments',  # Payment transactions
    'reviews',  # Reviews and ratings
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')
if DB_ENGINE.endswith('sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.getenv('DB_SSLMODE', 'prefer'),
            },
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        }
    }



# Password validation
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads - documents, images, etc.)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security headers/cookies
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = _env_bool('CSRF_COOKIE_HTTPONLY', False)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Session auth for browser
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny' if DEBUG else 'rest_framework.permissions.IsAuthenticated',
    ],
}

# Didit Identity Verification Settings
# Session-based KYC flow
DIDIT_ENABLED = _env_bool('DIDIT_ENABLED', False)
DIDIT_API_KEY = os.getenv('DIDIT_API_KEY', '')
DIDIT_API_ID = os.getenv('DIDIT_API_ID', '')
DIDIT_WORKFLOW_ID = os.getenv('DIDIT_WORKFLOW_ID', '')
DIDIT_WEBHOOK_SECRET = os.getenv('DIDIT_WEBHOOK_SECRET', '')
DIDIT_BASE_URL = os.getenv('DIDIT_BASE_URL', 'https://verification.didit.me')
DIDIT_AUTH_URL = os.getenv('DIDIT_AUTH_URL', 'https://auth.didit.me')
DIDIT_ALLOW_MOCK_FALLBACK = _env_bool('DIDIT_ALLOW_MOCK_FALLBACK', DEBUG)
BACKEND_BASE_URL = os.getenv('BACKEND_BASE_URL', 'http://127.0.0.1:8000')

# Papertrail logging (works on Render free by sending logs directly from app).
PAPERTRAIL_ENABLED = _env_bool('PAPERTRAIL_ENABLED', False)
PAPERTRAIL_HOST = os.getenv('PAPERTRAIL_HOST', '').strip()
PAPERTRAIL_PORT = int(os.getenv('PAPERTRAIL_PORT', '0') or 0)
PAPERTRAIL_APP_NAME = os.getenv('PAPERTRAIL_APP_NAME', 'servigo-backend').strip() or 'servigo-backend'
PAPERTRAIL_LEVEL = os.getenv('PAPERTRAIL_LEVEL', 'INFO').upper()

# Third-party integrations
# Twilio SMS Settings (for OTP delivery) - set SMS_OTP_ENABLED=True to enable
SMS_OTP_ENABLED = _env_bool('SMS_OTP_ENABLED', False)  # Master flag: enable/disable SMS OTP sending
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')  # e.g., '+14782155819'

# Keep non-OTP SMS off by default to protect Twilio credits.
SMS_NON_OTP_NOTIFICATIONS_ENABLED = _env_bool('SMS_NON_OTP_NOTIFICATIONS_ENABLED', False)

# MailerSend worker notification email (new booking + cancellation)
WEBLAB_WORKER_JOB_EMAIL_ENABLED = _env_bool('WEBLAB_WORKER_JOB_EMAIL_ENABLED', False)
MAILERSEND_API_TOKEN = os.getenv('MAILERSEND_API_TOKEN', '')
MAILERSEND_FROM_EMAIL = os.getenv('MAILERSEND_FROM_EMAIL', '')
MAILERSEND_FROM_NAME = os.getenv('MAILERSEND_FROM_NAME', 'Service Provider App')

# Razorpay WebLab switch (keep OFF to preserve current flow)
WEBLAB_RAZORPAY_ENABLED = _env_bool('WEBLAB_RAZORPAY_ENABLED', False)
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')

FIREBASE_PHONE_AUTH_ENABLED = _env_bool('FIREBASE_PHONE_AUTH_ENABLED', False)
# Keep OTP visible in API responses only for demo/testing flows.
OTP_EXPOSE_IN_API = _env_bool('OTP_EXPOSE_IN_API', False)
SUREPASS_API_TOKEN = os.getenv('SUREPASS_API_TOKEN', '')
SUREPASS_BASE_URL = os.getenv('SUREPASS_BASE_URL', 'https://kyc-api.surepass.io/api/v1')
BUSINESS_UPI_ID = os.getenv('BUSINESS_UPI_ID', '')
BUSINESS_NAME = os.getenv('BUSINESS_NAME', 'HomeServices')
FCM_SERVER_KEY = os.getenv('FCM_SERVER_KEY', '')

# Booking policy
CANCELLATION_FEE_PERCENT = float(os.getenv('CANCELLATION_FEE_PERCENT', '20'))
ADMIN_CUT_PERCENT = float(os.getenv('ADMIN_CUT_PERCENT', '2'))


_logging_handlers = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    },
}

_root_handlers = ['console']

if PAPERTRAIL_ENABLED and PAPERTRAIL_HOST and PAPERTRAIL_PORT > 0:
    _logging_handlers['papertrail'] = {
        'class': 'logging.handlers.SysLogHandler',
        'formatter': 'papertrail',
        'address': (PAPERTRAIL_HOST, PAPERTRAIL_PORT),
        'socktype': 2,  # socket.SOCK_DGRAM
    }
    _root_handlers.append('papertrail')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
        'papertrail': {
            'format': f'{PAPERTRAIL_APP_NAME}: %(name)s [%(levelname)s] %(message)s',
        },
    },
    'handlers': _logging_handlers,
    'root': {
        'handlers': _root_handlers,
        'level': PAPERTRAIL_LEVEL,
    },
}
