# Generated by Django 6.0.1 on 2026-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='authentication.appuser')),
            ],
            options={
                'db_table': 'wallet_transactions',
                'managed': True,
                'indexes': [models.Index(fields=['user'], name='wallet_tran_user_id_97baf4_idx'), models.Index(fields=['type'], name='wallet_tran_type_be1dd4_idx'), models.Index(fields=['created_at'], name='wallet_tran_created_33245a_idx')],
            },
        ),
    ]
